name: UltimateTag
version: 1.0.0
main: dev.raegous.tag.UltimateTagPlugin
commands:
  tag:
    description: Tags a player
    usage: /<tag> [player]
    permission: ultimatetag.tag
    permission-message: You don't have permission to change who is it

permissions:
  ultimatetag.tag:
    description: Allows you to change who is it
    default: op